#====================================================================================
# Environment Setting
#====================================================================================
development:
    web_server:            127.0.0.1:3000
    file_server:           127.0.0.1
    file_server_user:      "Marchi"
    ssh_key:               "/Users/Marchi/Desktop/Akamai/ssh-keys/netstorage_key"

    video_library:        "/Volumes/Internal HD/Videos"
    
production:
    web_server:            118.142.104.200
    file_server:           118.142.104.200
    file_server_user:      "WMS"
    ssh_key:               "/Library/WebServer/Documents/video-system/shared/ssh-key/netstorage_key"
    
    video_library:        "/Volumes/Internal HD/Videos"
